/*
 * Generated by Bluespec Compiler, version 2022.01-29-gc526ff54 (build c526ff54)
 * 
 * On Wed Aug  9 18:35:03 KST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "mkDut.h"


/* Constructor */
MOD_mkDut::MOD_mkDut(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_f_in(simHdl, "f_in", this, 32u, 2u, (tUInt8)1u, 0u),
    INST_f_out(simHdl, "f_out", this, 32u, 2u, (tUInt8)1u, 0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 3u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkDut::init_symbols_0()
{
  init_symbol(&symbols[0u], "f_in", SYM_MODULE, &INST_f_in);
  init_symbol(&symbols[1u], "f_out", SYM_MODULE, &INST_f_out);
  init_symbol(&symbols[2u], "RL_compute", SYM_RULE);
}


/* Rule actions */

void MOD_mkDut::RL_compute()
{
  tUInt32 DEF_IF_f_in_first_EQ_20_THEN_f_in_first_PLUS_2_ELS_ETC___d8;
  tUInt32 DEF_f_in_first____d4;
  DEF_f_in_first____d4 = INST_f_in.METH_first();
  DEF_IF_f_in_first_EQ_20_THEN_f_in_first_PLUS_2_ELS_ETC___d8 = DEF_f_in_first____d4 == 20u ? DEF_f_in_first____d4 + 2u : DEF_f_in_first____d4 + 1u;
  INST_f_in.METH_deq();
  INST_f_out.METH_enq(DEF_IF_f_in_first_EQ_20_THEN_f_in_first_PLUS_2_ELS_ETC___d8);
}


/* Methods */

void MOD_mkDut::METH_request_put(tUInt32 ARG_request_put)
{
  INST_f_in.METH_enq(ARG_request_put);
}

tUInt8 MOD_mkDut::METH_RDY_request_put()
{
  tUInt8 DEF_CAN_FIRE_request_put;
  tUInt8 PORT_RDY_request_put;
  DEF_CAN_FIRE_request_put = INST_f_in.METH_i_notFull();
  PORT_RDY_request_put = DEF_CAN_FIRE_request_put;
  return PORT_RDY_request_put;
}

tUInt32 MOD_mkDut::METH_response_get()
{
  tUInt32 DEF_response_get__avValue1;
  tUInt32 PORT_response_get;
  DEF_response_get__avValue1 = INST_f_out.METH_first();
  PORT_response_get = DEF_response_get__avValue1;
  INST_f_out.METH_deq();
  return PORT_response_get;
}

tUInt8 MOD_mkDut::METH_RDY_response_get()
{
  tUInt8 DEF_CAN_FIRE_response_get;
  tUInt8 PORT_RDY_response_get;
  DEF_CAN_FIRE_response_get = INST_f_out.METH_i_notEmpty();
  PORT_RDY_response_get = DEF_CAN_FIRE_response_get;
  return PORT_RDY_response_get;
}


/* Reset routines */

void MOD_mkDut::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_f_out.reset_RST(ARG_rst_in);
  INST_f_in.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkDut::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkDut::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_f_in.dump_state(indent + 2u);
  INST_f_out.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkDut::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 3u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  num = INST_f_in.dump_VCD_defs(num);
  num = INST_f_out.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkDut::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDut &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkDut::vcd_defs(tVCDDumpType dt, MOD_mkDut &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}

void MOD_mkDut::vcd_prims(tVCDDumpType dt, MOD_mkDut &backing)
{
  INST_f_in.dump_VCD(dt, backing.INST_f_in);
  INST_f_out.dump_VCD(dt, backing.INST_f_out);
}
